name: refactoring
description: A sample command-line application.
version: 1.0.0
homepage: wrike.com
author: Alexey Zolotykh <aazolotyh@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
 path: ^1.4.1
 source_gen: any
 analyzer: any
 mockito: "^3.0.0-beta"

dev_dependencies:
  test: ^0.12.30
